name: Run Tests

on:
  push:
    branches:
      - main # Change this to your default branch if it's different

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install pnpm
        run: |
          wget -qO- https://get.pnpm.io/install.sh | sh -

      - name: Install project dependencies
        run: pnpm install

      - name: Run Tests
        run: pnpm test
